# -*- coding: utf-8 -*-
"""Slide Maker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gr16CjVRypFdRM511AotTijXvXWTURdn
"""

# Record your slide
# Transcribe
# Put into a presentation

# Install the necessary libraries
#!pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2
#!pip install --upgrade google-cloud-speech
#!sudo apt install portaudio19-dev
#!pip install pyaudio
#!pip -q install pydub # This is the package that enables live recording
#!pip install numpy openai-whisper soundfile # This is the package that converts the live stream into a wav file

from base64 import b64decode
from io import BytesIO
from pydub import AudioSegment

import io
import numpy as np
import whisper
import soundfile as sf
from openai import OpenAI
import openai

import os, getpass
import tempfile
from pydub import AudioSegment

from google.oauth2 import service_account
from googleapiclient.discovery import build
import re
import json


def _set_env(var: str):
  if not os.environ.get(var):
    os.environ[var] = getpass.getpass(f"{var}: ")


_set_env("OPENAI_API_KEY")

import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))

# Grant access to tools
SCOPES = [
    'https://www.googleapis.com/auth/presentations',
    'https://www.googleapis.com/auth/drive'
]

credentials = service_account.Credentials.from_service_account_file(
    service_account_path, scopes=SCOPES)

service_account_path = '/content/slidemakr-ac7d7a834a05.json'

# Audio processing is now handled by recorder.js in the frontend

# So basically, instead of creating a temporary buffer file, it creates a temporary wav file
# 2. Convert audio to WAV format
# Instead of using openai for the conversion, use pydub directly
def convert_audio_segment_to_wav(audio_segment, sample_rate=16000):
  # Set the sample rate if it's different from the original
  if audio_segment.frame_rate != sample_rate:
    audio_segment = audio_segment.set_frame_rate(sample_rate)

  # Create a temporary WAV file
  with tempfile.NamedTemporaryFile(suffix=".wav",
                                   delete=False) as tmp_wav_file:
    # Export audio directly to the WAV file
    audio_segment.export(tmp_wav_file.name, format="wav")
    wav_path = tmp_wav_file.name

  return wav_path

# 3. Transcribe audio
def transcribe_audio(wav_buffer):
  # Transcribe audio using OpenAI API
  with open(wav_buffer, "rb") as wav_file:
    try:
      response = client.audio.transcriptions.create(model="whisper-1",
                                                    file=wav_file,
                                                    response_format="text")
      print(response)
    except Exception as e:
      print(f"An error occurred: {e}")
  return response



# Step 4: Use GPT to generate Google Slides creation code from transcription instructions
def generate_code_from_instructions(instructions_text):
  response = client.chat.completions.create(model="gpt-4o",
                                            messages=[{
                                                "role":
                                                "system",
                                                "content": [{
                                                    "type":
                                                    "text",
                                                    "text":
                                                    """
                        You are an engineer, create a list of requests in python code that makes the content of a
                        Google slides presentation from the human instructions.
                        The code will be used as content for requests in another function where we call the Google API so in your response start immediately with the code like this: ['{
                        'createSlide':'. Do not include the 'request = []', or any text, like '''json, just the list.
                        Please format the output as valid JSON
                        with double quotes for all property names and string values.
                        Every item in the request list should be formatted as a dictionary of dictionaries, like this {{}}.
                        Here is an example of a request item for createSlide: {
                          "createSlide": {
                              "objectId": f"slide_{len(requests)}",
                              "slideLayoutReference": {
                                  "predefinedLayout": slide_info.get("slideType", "BLANK")
                              }
                          }
                      } Thank you!"""
                                                }]
                                            }, {
                                                "role":
                                                "user",
                                                "content": [{
                                                    "type":
                                                    "text",
                                                    "text":
                                                    f"{instructions_text}"
                                                }]
                                            }],
                                            response_format={"type": "text"},
                                            temperature=0,
                                            max_completion_tokens=2048,
                                            top_p=1,
                                            frequency_penalty=0,
                                            presence_penalty=0)
  generated_code = response.choices[0].message.content
  cleaned_result = re.sub(r'^```python\n|```$',
                          '',
                          generated_code,
                          flags=re.MULTILINE)
  return cleaned_result.strip()

# Step 5: Make the slides

def run_generated_code(generated_code, credentials):
  slides_service = build('slides', 'v1', credentials=credentials)

  # Build the service
  service = build('slides', 'v1', credentials=credentials)

  # Create a presentation
  presentation = service.presentations().create(body={
      'title': 'Sample Presentation'
  }).execute()
  presentation_id = presentation['presentationId']

  # Parse the JSON string
  data = json.loads(code)

  for index, i in enumerate(data):
    print(i)
    try:
      requests = [i]
      response = service.presentations().batchUpdate(
          presentationId=presentation_id, body={
              'requests': requests
          }).execute()
      print(f"Successfully executed {len(requests)} requests")
    except:
      print(f"Error in request {index}")
      continue
  url = f'https://docs.google.com/presentation/d/{presentation_id}/edit'
  return presentation_id, url

# 6. Send presentation

def share_presentation(presentation_id, email, credentials):
  drive_service = build('drive', 'v3', credentials=credentials)
  drive_service.permissions().create(fileId=f'{presentation_id}',
                                     body={
                                         'type': 'user',
                                         'role': 'writer',
                                         'emailAddress': f'{email}'
                                     },
                                     fields='id').execute()


"""# This is V1 Agent
- It runs the program linearlly
- We are not correcting for mistakes in the presentation
- We are not accounting for prompt length
"""

# Run everything
# 1. Generate Audio
audio = record_until_silence()
# 2. Convert to Wav
wav_buffer = convert_audio_segment_to_wav(audio)
# 3. Transcribe Audio
instructions = transcribe_audio(wav_buffer)
# 4. Generate code
code = generate_code_from_instructions(instructions)
# 5 Generate Slides
presentation_id, url = run_generated_code(code, credentials)
# 6. Share Slides
email = input("Please share your email")

share_presentation(presentation_id, email, credentials)

#### ADD THIS CODE LATER ####
# Maybe do this later
# Check if audio was retained
#raw_samples = np.array(audio.get_array_of_samples())

#if os.path.getsize(wav_buffer) == 0:
#  print("Warning: The output WAV file is empty.")
#else:
  # Check duration and amplitude
#  with sf.SoundFile(wav_buffer) as f:
#    duration = len(f) / 16000  # Calculate duration in seconds
#    if duration == 0:
#      print("Warning: The audio has zero duration.")
#    elif not np.any(raw_samples):  # Check if all samples are zero
#      print("Warning: The audio is silent.")
#    else:
#      print(f"Audio retained with duration: {duration:.2f} seconds.")
#new_audio = AudioSegment.from_wav(wav_buffer)

