# -*- coding: utf-8 -*-
"""Slide Makr Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjgp8qPiGNYEYETZijlCwKEdSdYhNkM3
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture --no-stderr
# %pip install --quiet -U langchain_openai langchain_core langgraph

from typing_extensions import TypedDict
from google.oauth2.service_account import Credentials
from google.oauth2 import service_account
from googleapiclient.discovery import Resource, build
import re
import json
import os

# Imports for building the graph
from langgraph.graph import StateGraph, START, END
from langgraph.graph import MessagesState
from langgraph.prebuilt import ToolNode,  tools_condition # Enable it to actually run the tool pre-built function in langraph that says continue until no tool call is returned

from typing import Annotated, Optional
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, AnyMessage
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import Command, interrupt
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

# At the top of your file, import dotenv
from dotenv import load_dotenv
# Then load the variables from .env
load_dotenv()
service_account_path = os.getenv("SERVICE_ACCOUNT_PATH")


# 1. Set the model
llm = ChatOpenAI(model="gpt-4", temperature=0, max_tokens=2048)

# 2. Define the class which includes all the functions I want to use
# Basically, these are all the tools I need to build slidemakr
class Slidemakr:

    def __init__(self, service_account_path):
        SCOPES = [
            'https://www.googleapis.com/auth/presentations',
            'https://www.googleapis.com/auth/drive'
        ]
        self.credentials = service_account.Credentials.from_service_account_file(
            service_account_path, scopes=SCOPES
        )
        self.slides_service = build('slides', 'v1', credentials=self.credentials)
        self.drive_service = build('drive', 'v3', credentials=self.credentials)

    def generate_code(self, instructions: str) -> str:
        """Generates code based on human instructions for Google Slides."""
        messages = [
            SystemMessage(content=""""You are an engineer, create a list of requests in python code that makes the content of a
                        Google slides presentation from the human instructions.
                        The code will be used as content for requests in another function where we call the Google API so in your response start immediately with the code like this: ['{
                        'createSlide':'. Do not include the 'request = []', or any text, like '''json, just the list.
                        Please format the output as valid JSON
                        with double quotes for all property names and string values.
                        Every item in the request list should be formatted as a dictionary of dictionaries, like this {{}}.
                        Here is an example of a request item for createSlide: {
                          "createSlide": {
                              "objectId": f"slide_{len(requests)}",
                              "slideLayoutReference": {
                                  "predefinedLayout": slide_info.get("slideType", "BLANK")
                              }
                          }
                      } Thank you!""", name="Model"),
            HumanMessage(content=instructions)
        ]
        response = llm.invoke(messages)
        generated_code = response.content
        cleaned_code = re.sub(r'^```python\n|```$', '', generated_code, flags=re.MULTILINE)
        return cleaned_code

    def create_presentation(self) -> str:
        """Creates a new Google Slides presentation."""
        presentation = self.slides_service.presentations().create(
            body={'title': 'Your Presentation'}
        ).execute()
        presentation_id = presentation['presentationId']
        return presentation_id

    def run_generated_code(self, generated_code: str, presentation_id: str) -> tuple[str, dict]:
        """Executes the generated code to update the presentation."""
        try:
            requests = json.loads(generated_code)
        except json.JSONDecodeError as e:
            return "", {"json_error": str(e)}

        errors = {}
        for index, req in enumerate(requests):
            try:
                self.slides_service.presentations().batchUpdate(
                    presentationId=presentation_id,
                    body={'requests': [req]}
                ).execute()
            except Exception as e:
                errors[str(req)] = str(e)
        url = f'https://docs.google.com/presentation/d/{presentation_id}/edit'
        return url, errors


    def share_presentation(self, presentation_id: str, email: str) -> dict:
        """Shares the presentation with a given email address."""
        try:
            self.drive_service.permissions().create(
                fileId=presentation_id,
                body={'type': 'user', 'role': 'writer', 'emailAddress': email},
                fields='id'
            ).execute()
            return {"status": "shared"}
        except Exception as e:
            return {"error": str(e)}

# 3. Based on the functions in the class, define the tools that can be used,
# Still need to instantiate them.
slide_tools = Slidemakr(service_account_path)

@tool
def generate_code_tool(instructions: str) -> str:
    "Creates the python code needed to build the slides"
    return slide_tools.generate_code(instructions)

@tool
def create_presentation_tool() -> str:
    "Once the python code is created, this creates a new presentation"
    return slide_tools.create_presentation()

@tool
def run_generated_code_tool(generated_code: str, presentation_id: str) -> tuple[str, dict]:
    "Once the presentation is created, this executes the code made in generate_code_tool"
    return slide_tools.run_generated_code(generated_code, presentation_id)


# 4. Bind tools to the model
llm_with_tools = llm.bind_tools([
    generate_code_tool,
    create_presentation_tool,
    run_generated_code_tool
])

# 5. Build the graph
# If the agent is in charge, it decides everything. If we want more control, we specify the agent prompt to work through specific steps
# Tell the LLM how you want to build the presentation, with this level of being in charge, almost makes it non-sensical to let them "decide"
agent_system_prompt = """You are an engineer that creates Google Slides presentations based on user instructions.
Your task is to:
1. Generate the code for the presentation based on user instructions using the generate_code_tool
2. Create a new presentation using the create_presentation_tool, if one doesn't exist already
3. Run the generated code to build the presentation using the run_generated_code_tool with the generated code and presentation ID
4. If there are errors, fix the code and then re-run the section that had errors
5. Once all errors have been resolved ask for the user's email to share the presentation

IMPORTANT: Always follow this exact sequence of steps in order. Do not skip any steps.
"""

# Define the variables we want to preserve in the agent
# The way I understand this is that these are the variables I keep
class SlideMakrState(MessagesState):
    generated_code: Optional[str] = None
    presentation_id: Optional[str] = None
    url: Optional[str] = None
    errors: Optional[dict] = None
    email: Optional[str]

# Node
def code_creating_llm(state: SlideMakrState):
    # Get the latest messages
    messages = state["messages"]

    # Add system message to the top of the chat
    if not any(isinstance(msg, SystemMessage) for msg in messages):
        messages.insert(0, SystemMessage(content=AGENT_SYSTEM_PROMPT))

    # Invoke them --> Aka run them
    result = llm_with_tools.invoke(state["messages"])

    # Return the messages and the response. 
    # To be honest. Given how long the presentation can be, I probably don't want the code to be shared!
    return {"messages": state["messages"] + [response]}

# Makes a decision on whether or not to share
def custom_tools_condition(state: SlideMakrState) -> str:
    last_message = state["messages"][-1]
    # If the LLM is calling tools, return "tools" node
    if isinstance(last_message, AIMessage) and last_message.tool_calls:
        return "tools"
    # Otherwise, go to a different node of your choice (e.g., "get_email")
    return "get_email"

def extract_results(state: SlideMakrState):
    presentation_id = None
    url = None

    for message in state["messages"]:
        if  message.name == "create_presentation_tool":
            presentation_id = message.content
        
        elif message.name == "run_generated_code_tool":
            try:
                url = json.loads(message.content)
            except:
                pass

    return {
        "presentation_id": presentation_id,
        "url": url,
        "messages": state["messages"]
    }

# This is the node from the user that updates with the email
def get_email(state: SlideMakrState):
    email = interrupt(
        # This value will be sent to the client
        # as part of the interrupt information.
        {"Can you give me the email address I should share this with?"
        }
    )
    return {"email": email, "messages": state["messages"]+[HumanMessage(content=email)]} 
    

# Node: Execute share function (not a tool)
def share_presentation_node(state: SlideMakrState):
    "After the presentation has been generated, share it back with the user"
    # Extract latest human message (email)
    # Shoule be safe to do given previous step was add email
    email = state.get("email")
    presentation_id = state.get("presentation_id")

    slide_tools.share_presentation(presentation_id, email)
    return {"messages": [AIMessage(content=f"Presentation shared with {email}.")]}


# Build graph
builder = StateGraph(SlideMakrState)
builder.add_node("code_creating_llm", code_creating_llm)
builder.add_node("tools", ToolNode([generate_code_tool,create_presentation_tool,run_generated_code_tool])) # Add a node that actually executes
builder.add_node("get_email", get_email) # Node that gets user input
builder.add_node("share_presentation_node", share_presentation_node) # Function that shares the presentation
builder.add_node("extract_results", extract_results) # Function that shares the presentation

builder.add_edge(START, "code_creating_llm") # The first step is always to create the code
builder.add_conditional_edges("code_creating_llm",custom_tools_condition) # I have to make a new function here.
builder.add_edge("tools", "code_creating_llm")

# Step 5: After user responds with email, run share tool
builder.add_edge("get_email","share_presentation_node")
builder.add_edge("share_presentation_node", END)

# 1. Compile the graph with interrupt_before

graph = builder.compile()

#def fix_code(errors):
#  """Function that fixes code"""
#  if len(errors) == 0:
#    return share_presentation
#  else:
#    override instructions message
#    instructions = "The code failed with this error {error}, please re-create the code for this part"
#    return run generate_code